"""empty message

Revision ID: 36523e1f151b
Revises: 3ba71cdac550
Create Date: 2013-11-26 00:29:21.953724

"""

# revision identifiers, used by Alembic.
revision = '36523e1f151b'
down_revision = '3ba71cdac550'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
