"""empty message

Revision ID: 3ba71cdac550
Revises: None
Create Date: 2013-11-26 00:15:15.543585

"""

# revision identifiers, used by Alembic.
revision = '3ba71cdac550'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
