"""empty message

Revision ID: 482cadc3acd3
Revises: 36523e1f151b
Create Date: 2013-12-02 18:09:16.122744

"""

# revision identifiers, used by Alembic.
revision = '482cadc3acd3'
down_revision = '36523e1f151b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'roles')
    op.drop_table(u'pages')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'pages',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'title', sa.VARCHAR(length=255), nullable=True),
    sa.Column(u'description', sa.TEXT(), nullable=True),
    sa.Column(u'date', sa.DATETIME(), nullable=True),
    sa.Column(u'category_id', sa.INTEGER(), nullable=True),
    sa.Column(u'active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], [u'categories.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'roles',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'name', sa.VARCHAR(length=255), nullable=True),
    sa.Column(u'description', sa.VARCHAR(length=255), nullable=True),
    sa.Column(u'active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
